spring.application.name=finance-dashboard

# H2 Database config
spring.datasource.url=jdbc:h2:mem:finance_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=vaishnavv
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
